version: '2.2'
services:
### Logging ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:5.6.3
    volumes:
      - ./container/volumes/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./container/volumes/logstash/pipeline:/usr/share/logstash/pipeline
    expose:
      - 6000
    ports:
      - 6000:6000
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:5.6.3
    volumes:
      - ./container/volumes/kibana/config/:/usr/share/kibana/config
    ports:
      - 5601:5601

