#!/usr/bin/env bash

echo "Creating database kuberweb..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database kuberweb-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://jedi@localhost:5432/kuberweb-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
